In [2]:
import numpy as np
import pandas as pd
import plotly.express as px

In [3]:
df = pd.read_csv('DataCoSupplyChainDataset.csv', encoding='ISO-8859-1')
df

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/15/2018 11:24,Standard Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

In [ ]:
###Exploring Data
# ? This comment turns blue (Questions/Queries)

### Exploring data

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [38]:
df.groupby('Customer Fname')['Sales per customer'].sum().sort_values(ascending=False).head(10).reset_index()

  Customer Fname  Sales per customer
0           Mary        1.166951e+07
1          James        3.263113e+05
2         Robert        3.177447e+05
3        Michael        3.022219e+05
4          David        2.885049e+05
5           John        2.629035e+05
6        William        2.442043e+05
7         Joseph        1.974473e+05
8       Jennifer        1.910223e+05
9        Richard        1.860018e+05

In [39]:
df.groupby('Order Country')['Sales'].sum().sort_values(ascending=False).reset_index().round(10)

         Order Country         Sales
0       Estados Unidos  4.879668e+06
1              Francia  2.879942e+06
2               México  2.633195e+06
3             Alemania  2.074172e+06
4            Australia  1.694622e+06
..                 ...           ...
159             Kuwait  3.349600e+02
160  Guinea Ecuatorial  3.199600e+02
161            Eritrea  3.099600e+02
162            Burundi  2.999500e+02
163             Serbia  1.200000e+02

[164 rows x 2 columns]

In [40]:
real_top_buyers = df.groupby(['Customer Id', 'Customer Fname', 'Customer Lname','Order Country'])['Sales per customer'].sum().sort_values(ascending=False).head(10)
real_top_buyers

Customer Id  Customer Fname  Customer Lname  Order Country
11430        Mary            Miller          Estados Unidos    4860.360039
10198        Mary            Smith           Estados Unidos    3794.200058
11768        Virginia        Smith           Estados Unidos    3310.830067
1540         Mary            Mckee           Estados Unidos    3296.500078
5640         Matthew         Smith           Estados Unidos    3167.400040
11132        Jonathan        Washington      Estados Unidos    3148.710037
12180        Mary            Allen           Estados Unidos    3130.020042
2484         Sarah           Smith           Alemania          3040.120041
4943         Paul            Sosa            Estados Unidos    3003.440018
7082         Adam            Blair           Francia           2992.490059
Name: Sales per customer, dtype: float64

In [41]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

## Data checking & Cleaning (if any)

In [5]:
df[df.duplicated()]

Empty DataFrame
Columns: [Type, Days for shipping (real), Days for shipment (scheduled), Benefit per order, Sales per customer, Delivery Status, Late_delivery_risk, Category Id, Category Name, Customer City, Customer Country, Customer Email, Customer Fname, Customer Id, Customer Lname, Customer Password, Customer Segment, Customer State, Customer Street, Customer Zipcode, Department Id, Department Name, Latitude, Longitude, Market, Order City, Order Country, Order Customer Id, order date (DateOrders), Order Id, Order Item Cardprod Id, Order Item Discount, Order Item Discount Rate, Order Item Id, Order Item Product Price, Order Item Profit Ratio, Order Item Quantity, Sales, Order Item Total, Order Profit Per Order, Order Region, Order State, Order Status, Order Zipcode, Product Card Id, Product Category Id, Product Description, Product Image, Product Name, Product Price, Product Status, shipping date (DateOrders), Shipping Mode]
Index: []

[0 rows x 53 columns]

In [6]:
df.isna().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

##Dropping Fake Data

### Getting Insights from the data

In [79]:
df.groupby ('Country')[['PaymentMethod']].value_counts().sort_values(ascending=False).reset_index()

           Country     PaymentMethod  count
0    United States       Credit Card  24585
1    United States        Debit Card  14002
2    United States        Amazon Pay  10559
3    United States               UPI  10532
4    United States       Net Banking   6975
5            India       Credit Card   5223
6    United States  Cash on Delivery   3405
7            India        Debit Card   2996
8            India               UPI   2303
9            India        Amazon Pay   2257
10          Canada       Credit Card   2018
11  United Kingdom       Credit Card   1737
12           India       Net Banking   1492
13       Australia       Credit Card   1475
14          Canada        Debit Card   1178
15  United Kingdom        Debit Card   1004
16          Canada               UPI    877
17          Canada        Amazon Pay    850
18       Australia        Debit Card    844
19           India  Cash on Delivery    780
20  United Kingdom               UPI    767
21  United Kingdom        Amazon Pay    732
22       Australia        Amazon Pay    619
23          Canada       Net Banking    600
24       Australia               UPI    587
25  United Kingdom       Net Banking    474
26       Australia       Net Banking    386
27          Canada  Cash on Delivery    295
28  United Kingdom  Cash on Delivery    229
29       Australia  Cash on Delivery    219

In [82]:
df.groupby('City')['ShippingCost'].sum().sort_values(ascending=False)

City
Charlotte        38142.49
San Jose         37862.29
Columbus         37665.17
Dallas           37519.13
Austin           37473.88
Jacksonville     37390.66
Seattle          37358.87
Los Angeles      37357.13
Philadelphia     37264.66
Chicago          37251.50
New York         37105.35
Denver           37098.39
Houston          36876.03
Washington       36836.31
Indianapolis     36622.39
Phoenix          36597.52
San Antonio      36497.55
San Francisco    36153.30
Fort Worth       35907.40
San Diego        35685.99
Name: ShippingCost, dtype: float64

In [ ]:
check the correlation between shipping cost and country

In [36]:
df.groupby('CustomerName')['OrderID'].count().sort_values(ascending=False)

CustomerName
Karan Joshi     556
Arjun Kumar     553
Pooja Kapoor    552
Rohit Gupta     547
Vihaan Singh    544
               ...
Kabir Patel     454
Aman Sharma     453
Sneha Singh     450
Sunita Reddy    440
Vikas Gupta     436
Name: OrderID, Length: 200, dtype: int64

In [39]:
df.groupby('CustomerName')['TotalAmount'].sum().sort_values(ascending=False).round(2)

CustomerName
Pooja Kapoor    547832.64
Vihaan Singh    526675.89
Pooja Singh     516451.45
Kabir Joshi     515361.68
Aditya Gupta    515005.09
                  ...
Sunita Reddy    403238.35
Kabir Reddy     399224.49
Ritika Mehta    391922.47
Vikas Gupta     389299.02
Rohit Joshi     376778.76
Name: TotalAmount, Length: 200, dtype: float64

In [77]:
df[df['CustomerName'] == 'Pooja Kapoor']['TotalAmount'].sum().round(2)

np.float64(547832.64)

In [23]:
df.groupby('Country')['OrderID'].count().sort_values(ascending=False)

Country
United States     70058
India             15051
Canada             5818
United Kingdom     4943
Australia          4130
Name: OrderID, dtype: int64

In [66]:
df.groupby('Country')['ShippingCost'].sum().sort_values(ascending=False)

Country
United States     519081.94
India             111216.10
Canada             43382.24
United Kingdom     36233.26
Australia          30752.47
Name: ShippingCost, dtype: float64

In [71]:
df['Category'].value_counts(normalize= True).round(4) * 100

Category
Electronics          16.85
Sports & Outdoors    16.80
Books                16.75
Home & Kitchen       16.61
Toys & Games         16.54
Clothing             16.44
Name: proportion, dtype: float64

In [85]:
df.groupby('Category')['TotalAmount'].sum().sort_values(ascending=False)

Category
Electronics          15584217.18
Sports & Outdoors    15345571.88
Books                15261837.01
Clothing             15253397.50
Toys & Games         15216684.99
Home & Kitchen       15163939.36
Name: TotalAmount, dtype: float64

### FEATURE ENGINEERING

#Christmas column